FROM apify/actor-node:20

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./ 

# Instalar dependências
RUN npm install --quiet --no-optional 

# Copiar o restante da aplicação
COPY . ./ 

# Executar npm list para verificar pacotes instalados (opcional, para depuração)
RUN npm list || true 

# Comando para executar a aplicação
CMD [ "node", "index.js" ]
