FROM apify/actor-node:20

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install --quiet --only=prod --no-optional

# Copy the rest of the application
COPY . ./

# Run npm list to check installed packages
RUN npm list || true

# Command to run the application
CMD [ "node", "index.js" ]